---
title: "R Notebook"
output: html_notebook
---


# setup

```{r}
library(ggplot2)
library(nlraa)
library(nlme)
library(mgcv)
```


## lm

```{r}
data(Oats, package = "nlme")
head(Oats)
```


```{r}
ggplot(Oats, aes(nitro, yield)) +
  geom_point() +
  facet_wrap(~Block)
```

```{r}
Oats.I <- subset(Oats, Block == "I")
Oats.I
```

```{r}
fm1 <- lm(yield ~ nitro, data = Oats.I)
fm1.prd <- predict(fm1, interval = "conf")
Oats.IA <- cbind(Oats.I, fm1.prd)
Oats.IA
```

```{r}
ggplot(Oats.IA, aes(x = nitro, y = yield)) +
  geom_ribbon(aes(ymin = lwr, ymax = upr), fill = "purple", alpha = 0.4) +
  geom_line(aes(y = fit)) +
  geom_point()
  
  
```

```{r}
ggplot(Oats.IA, aes(nitro, yield)) +
  geom_smooth(method = "lm") +
  geom_line(aes(y = fit)) +
  geom_point()
```

```{r}
fm1.prd.int <- predict(fm1, interval = "pred")
Oats.IAP <- cbind(Oats.I, fm1.prd.int)
Oats.IAP
```


```{r}
ggplot(data = Oats.IAP, aes(x = nitro, y = yield)) + 
  geom_ribbon(aes(ymin = lwr, ymax = upr), fill = "deepskyblue4", alpha = 0.2) + 
  geom_ribbon(aes(ymin = Oats.IA$lwr, ymax = Oats.IA$upr), fill = "deepskyblue", alpha = 0.6) + 
  geom_line(aes(y = fit), color = "white", size = 1.5) +
  geom_point() + 
  ggtitle("Regression Line, 95% Confidence and Prediction Bands")
```


```{r}
fm1.boot <- boot_lm(fm1, fitted)
fm1.boot.prd <- summary_simulate(t(fm1.boot$t))
Oats.IAB <- cbind(Oats.I, fm1.boot.prd)
Oats.IAB
```

```{r}
ggplot(Oats.IAB, aes(nitro, yield)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), fill = "deepskyblue", alpha = 0.6) +
  geom_line(aes(y = Estimate), color = "white", size = 1.5) +
  geom_point() +
  ggtitle("95% Bootstrapped Confidence Bands")
```


# 비선형 예: Loblolly

```{r}
Lob <- subset(Loblolly, Seed %in% c("301", "303", "305", "307", "309"))
fnlm1 <- nls(height ~ SSasymp(age, Asym, R0, lrc), data = Lob)
ggplot(Lob, aes(age, height)) +
  geom_line(aes(y = fitted(fnlm1))) +
  geom_point()
```

```{r}
Lob.bt.pe <- boot_nls(fnlm1)
Lob.bt.pe
```


```{r}
pairs(Lob.bt.pe$t, labels = c("Asym", "R0", "lrc"))
```

```{r}
print(cov2cor(var(Lob.bt.pe$t)), digits = 2) ## Correlation matrix
```


```{r}
fm1.Lob <- lm(height ~ poly(age, 3), data = Lob)
fm1.Lob.prd <- predict(fm1.Lob, interval = "conf")
fm1.Lob.dat <- data.frame(method = "lm-poly(3)", Lob, fm1.Lob.prd)
fm1.Lob.dat
```

```{r}
fm2.Lob <- nls(height ~ SSasymp(age, Asym, R0, lrc), data = Lob)
fm2.Lob.dm <- predict2_nls(fm2.Lob, interval = "conf")
fm2.Lob.dm.dat <- data.frame(method = "Delta-Method", Lob,
                             fit = fm2.Lob.dm[,1],
                             lwr = fm2.Lob.dm[,3],
                             upr = fm2.Lob.dm[,4])
fm2.Lob.dm.dat
```

```{r}
fm2.Lob <- nls(height ~ SSasymp(age, Asym, R0, lrc), data = Lob)
fm2.Lob.bt <- boot_nls(fm2.Lob, fitted)
fm2.Lob.prd <- summary_simulate(t(fm2.Lob.bt$t))
fm2.Lob.bt.dat <- data.frame(method = "nls-bootstrap", Lob,
                             fit = fm2.Lob.prd[,1],
                             lwr = fm2.Lob.prd[,3],
                             upr = fm2.Lob.prd[,4])
fm2.Lob.bt.dat
```


```{r}
fm2.Lob.MC <- predict_nls(fm2.Lob, interval = "conf")
fm2.Lob.MC.dat <- data.frame(method = "nls-Monte-Carlo", Lob,
                          fit = fm2.Lob.MC[,1], 
                          lwr = fm2.Lob.MC[,3],
                          upr = fm2.Lob.MC[,4])
fm2.Lob.MC.dat
```

```{r}
fm3.Lob <- gam(height ~ s(age, k = 3), data = Lob)
fm3.Lob.prd <- predict(fm3.Lob, se.fit = TRUE)
fm3.Lob.GAM.dat <- data.frame(method = "GAM", Lob,
                              fit = fm3.Lob.prd$fit,
                              lwr = fm3.Lob.prd$fit - 2 * fm3.Lob.prd$se.fit,
                              upr = fm3.Lob.prd$fit + 2 * fm3.Lob.prd$se.fit)
fm3.Lob.GAM.dat
```


```{r}
prd.all <- rbind(fm1.Lob.dat, fm2.Lob.dm.dat, fm2.Lob.bt.dat, fm2.Lob.MC.dat, fm3.Lob.GAM.dat)
prd.all
```


```{r}
ggplot(prd.all, aes(age, height)) +
  facet_wrap(~method) +
  geom_line(aes(y = fit)) +
  geom_point() +
  geom_ribbon(aes(ymin = lwr, ymax = upr), fill = "purple", alpha = 0.5)
```

## 비선형 예: 퓨로마이신


```{r}
PurTrt <- Puromycin[Puromycin$state == "treated",]
fm1.P <- nls(rate ~ SSmicmen(conc, Vm, K), data = PurTrt)
summary(fm1.P)
```


```{r}
fm1.P.dm <- predict2_nls(fm1.P, interval = "conf")
round(predict2_nls(fm1.P, interval = "conf", newdata = data.frame(conc = 0.4)), 2)
```


```{r}
PurTrtA.dm <- cbind(PurTrt, fm1.P.dm)
ggplot(PurTrtA.dm, aes(conc, rate)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), fill = "purple", alpha = 0.2) +
  geom_line(aes(y = fitted(fm1.P))) +
  geom_point()
```

```{r}
fm1.P.bt <- boot_nls(fm1.P)
pairs(fm1.P.bt$t, labesl = c("Vm", "K"))
```


```{r}
fm1.P.bt.ft <- boot_nls(fm1.P, fitted)
fm1.P.bt.ft.prd <- summary_simulate(t(fm1.P.bt.ft$t))
PurTrtA <- cbind(PurTrt, fm1.P.bt.ft.prd)
```


```{r}
ggplot(PurTrtA, aes(conc, rate)) +
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), fill = "purple", alpha = 0.2) +
  geom_line(aes(y = fitted(fm1.P))) +
  geom_point()
```

```{r}
## predictions at 0.4
prd_fun <- function(x) predict(x, newdata = data.frame(conc = 0.4))
prd_fun(fm1.P)
```


```{r}
fm1.P.at.x.0.4 <- boot_nls(fm1.P, prd_fun)
boot::boot.ci(fm1.P.at.x.0.4, type = "perc")
```

```{r}
(prd.at.x.0.4 <- predict_nls(fm1.P, newdata = data.frame(conc = 0.4)))
```


```{r}
ndat <- data.frame(conc = seq(0, 1.3, length.out = 50))
Pprd <- predict_nls(fm1.P, interval = "conf",
                    newdata = ndat)
Pprdd <- data.frame(ndat, Pprd)
ggplot() + 
  geom_point(data = PurTrt, aes(x = conc, y = rate)) + 
  geom_line(data = Pprdd, aes(x = conc, y = Estimate)) + 
  geom_ribbon(data = Pprdd, aes(x = conc, ymin = Q2.5, ymax = Q97.5), 
              fill = "purple", alpha = 0.4) + 
  ggtitle("Monte Carlo 95% Confidence Bands")
```


## 비선형 예: 옥수수 잎 확장 비율

```{r}
data(maizeleafext)
## Display the data
fmm1 <- nls(rate ~ SStemp3(temp, t.m, t.l, t.h), data = maizeleafext)
ggplot(data = maizeleafext, aes(x = temp, y = rate)) + 
  geom_point() + geom_line(aes(y = fitted(fmm1)))
```

```{r}
## The model seems slightly inadequate for these data
fmm1.dm <- predict2_nls(fmm1, interval = "conf")
mlf <- cbind(maizeleafext, fmm1.dm)
## The confidence bands are significant
ggplot(data = mlf, aes(x = temp, y = rate)) + 
  geom_point() + geom_line(aes(y = fitted(fmm1))) + 
  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5), 
              fill = "purple", alpha = 0.3)
```


```{r}
## What about bootstrap?
fmm1.bt <- boot_nls(fmm1)
```

```{r}
## Notice that the model does not converge in many instances
pairs(fmm1.bt$t, labels = c("t.m", "t.l", "t.h"))
```


## 비선형 예: Theoph

```{r}
data(Theoph)
fmL.Theoph <- nlsList(conc ~ SSfol(Dose, Time, lKe, lKa, lCl), data = Theoph)
fm0.Theoph <- nlme(fmL.Theoph, random = pdDiag(lKa + lCl ~ 1))
## The Dose is different for each subject however...
ndat <- data.frame(Dose = median(Theoph$Dose), Time = seq(0, 25, by = 0.1))
fm0.Theoph.prd <- predict_nlme(fm0.Theoph, newdata = ndat, interval = "conf")
fm0.Theoph.prd.dat <- cbind(ndat, fm0.Theoph.prd)
## plot data
ggplot() + 
  geom_point(data = Theoph, aes(x = Time, y = conc)) + 
  geom_line(data = fm0.Theoph.prd.dat, aes(x = Time, y = Estimate)) + 
  geom_ribbon(data = fm0.Theoph.prd.dat,
              aes(x = Time, ymin = Q2.5, ymax = Q97.5), fill = "purple", alpha = 0.3) + 
  xlab("Time [h]") + ylab("Theophylline concentration [mg/L]") + 
  ggtitle("95% confidence bands")
```

```{r}
fm0.Theoph.prd.bnd <- predict_nlme(fm0.Theoph, plevel = 1, interval = "pred")
fm0.Theoph.prd.bnd.dat <- cbind(Theoph, fm0.Theoph.prd.bnd)
## Plot it
ggplot(data = fm0.Theoph.prd.bnd.dat, aes(x = Time, y = conc)) +
  facet_wrap(~Subject) + 
  geom_point() + 
  geom_line(aes(x = Time, y = Estimate)) + 
    geom_ribbon(data = fm0.Theoph.prd.bnd.dat,
              aes(x = Time, ymin = Q2.5, ymax = Q97.5), fill = "purple", alpha = 0.3) + 
  xlab("Time [h]") + ylab("Theophylline concentration [mg/L]") + 
  ggtitle("95% prediction bands (within subjects)")
```

```{r}
ndat <- expand.grid(Dose = median(Theoph$Dose), Time = 0:25, Subject = unique(Theoph$Subject))
ndat$Estimate <- predict(fm0.Theoph, newdata = ndat, level = 1)
fm0.Theoph.simA <- ndat
## Plot the simulations
ggplot() +
  geom_point(data = Theoph, aes(x = Time, y = conc)) +
  geom_line(
    data = fm0.Theoph.simA, aes(x = Time, y = Estimate, group = Subject),
    color = "gray"
  ) +
  geom_ribbon()
```
```{r}
pred_band_BS <- function(x) predict(x, newdata = ndat, level = 1)
fm0.Theoph.bt <- boot_nlme(fm0.Theoph, pred_band_BS, cores = 4)
```


```{r}
fm0.Theoph.bt.ss <- cbind(ndat[,-4], summary_simulate(t(na.omit(fm0.Theoph.bt$t))))
fm0.Theoph.bt.ss.A <- aggregate(cbind(Estimate, Est.Error, Q2.5, Q97.5) ~ Time, 
                                data = fm0.Theoph.bt.ss, FUN = mean)
## plot data
ggplot() + 
  geom_point(data = Theoph, aes(x = Time, y = conc)) + 
  geom_line(data = fm0.Theoph.bt.ss.A, aes(x = Time, y = Estimate)) + 
  geom_ribbon(data = fm0.Theoph.bt.ss.A, aes(x = Time, ymin = Q2.5, ymax = Q97.5), fill = "purple", alpha = 0.3) + 
  xlab("Time [h]") + ylab("Theophylline concentration [mg/L]") + 
  ggtitle("95% prediction bands (between subjects)")
```


# ----